name: Build and Deploy

on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Get packages
      run: |
        sudo apt install build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
        git clone https://github.com/raysan5/raylib.git raylib
        cd raylib
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON ..
        make
        sudo make install

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        ls build/ -a
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Balls
        tag_name: v1.0.0
        prerelease: false
        generate_release_notes: true
        files: build/balls
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_REPOSITORY: dhzdhd/balls
      
